### ISSUE TITLE
Bugjar crashes on swagger client instantiation

### ISSUE THREAD

**Issue by damienstanton** [pybee/bugjar#15]
I am using the [ARI-Py](https://github.com/asterisk/ari-py) and  [Swagger-Py](https://github.com/digium/swagger-py) libraries to interface with the Asterisk open-source phone system. When debugging one of my modules, Bugjar crashes with the following traceback:

``` shell
Traceback (most recent call last):
  File "C:\Python27\Scripts\bugjar-net-script.py", line 9, in <module>
    load_entry_point('bugjar==0.1.0', 'console_scripts', 'bugjar-net')()
  File "c:\python27\lib\site-packages\bugjar\main.py", line 153, in net
    net_run(options.hostname, options.port, filename, *options.args)
  File "c:\python27\lib\site-packages\bugjar\net.py", line 601, in run
    debugger.interaction(None, t)
  File "c:\python27\lib\site-packages\bugjar\net.py", line 226, in interaction
    self.output_stack()
  File "c:\python27\lib\site-packages\bugjar\net.py", line 161, in output_stack
    for frame, line_no in self.stack[str_index:]
  File "c:\python27\lib\site-packages\bugjar\net.py", line 150, in <genexpr>
    'locals': dict((k, repr(v)) for k, v in frame.f_locals.items()),
  File "build\bdist.win-amd64\egg\swaggerpy\client.py", line 189, in __repr__
  File "build\bdist.win-amd64\egg\swaggerpy\client.py", line 197, in __getattr__
```

... it then bounces between those last couple of lines several hundred times.

``` shell
File "build\bdist.win-amd64\egg\swaggerpy\client.py", line 214, in get_resource
  File "build\bdist.win-amd64\egg\swaggerpy\client.py", line 197, in __getattr__

RuntimeError: maximum recursion depth exceeded while calling a Python object
```

I know about the lack of tail recursion in the language, but everything works perfectly fine outside the debugger.

**Comment by damienstanton** [comment]
Never did reproduce this.
