### ISSUE TITLE
DistributionNotFound

### ISSUE THREAD

**Issue by trejoramiro** [pybee/bugjar#16]
# I ran >> bugjar in my terminal and received the message below. I thought I had successfully installed bugjar.
# Need help making sense of this Traceback. Thanks  **/

Traceback (most recent call last):
  File "/usr/local/bin/bugjar", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(**requires**)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: Pygments>=1.5
ramirotrejosmbp:Project1 ramirotrejo$ bugjar main.py arg1 arg2
Traceback (most recent call last):
  File "/usr/local/bin/bugjar", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(**requires**)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: Pygments>=1.5

**Comment by xenic** [comment]
I'm having a similar problem...  any thoughts about what I should try next?:


macBookPro$ pip install bugjar --upgrade
Requirement already up-to-date: bugjar in /Library/Python/2.7/site-packages
Requirement already up-to-date: Pygments>=1.5 in /Library/Python/2.7/site-packages (from bugjar)
Requirement already up-to-date: tkreadonly in /Library/Python/2.7/site-packages (from bugjar)
Cleaning up...
macBookPro$ bugjar guess.py
Traceback (most recent call last):
  File "/usr/local/bin/bugjar", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: tkreadonly
