### ISSUE TITLE
Fails to run when python3 is default on system

### ISSUE THREAD

**Issue by eddie-dunn** [pybee/bugjar#7]
This computer has python3 as the default python runtime. Trying to run bugjar triggers this error:

```
    from Tkinter import *
ImportError: No module named 'Tkinter'
```

From what I can deduce this is because with python3, Tkinter should be all lowercase, i.e. 'tkinter'.

**Comment by cajone** [comment]
I'm also experiencing this issue :+1: 

Traceback (most recent call last):
  File "/usr/bin/bugjar", line 9, in <module>
    load_entry_point('bugjar==0.1.0', 'console_scripts', 'bugjar')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/bugjar/main.py", line 4, in <module>
    from Tkinter import *
ImportError: No module named 'Tkinter'
